#!/usr/bin/env bash
# install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
