#!/usr/bin/env bash
# configure Nginx server for redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
sudo sed -i "\|^server {|a \ \ \ \ location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }" /etc/nginx/sites-available/default
sudo service nginx restart
