#!/usr/bin/env bash
# print "To infinity and beyond" indefinitely and "I am invincible!!!".

while true
do
	echo "infinity and beyond indefinitely"
	sleep 2
	trap "echo I am invincible!!!" SIGTERM
done
