#!/usr/bin/env bash
# FizzBuzz

for ((nbr = 1; nbr <= 100; nbr++))
do
	if ((nbr % 3 == 0)) && ((nbr % 5 == 0)); then
		echo "FizzBuzz"
	elif ((nbr % 3 == 0)); then
		echo "Fizz"
	elif ((nbr % 5 == 0)); then
		echo "Buzz"
	else
		echo "$nbr"
	fi
done
